name: Container registry login
description: Logs into a Azure Container Registry (ACR)
author: Digdir Platform Team

runs:
  using: composite
  steps:
     - name: Login to Azure
       uses: azure/login@v2
       with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

     - name: Login to Azure Container Registry
       shell: bash
       run: az acr login --name "$ACR_NAME"
       env:
        ACR_NAME: ${{ vars.ACR_NAME }}