name: Image signing
description: Composite action for image signing using Cosign
author: Digdir Platform Team

inputs:
  image:
    description: Valid image string for signing
    required: true

runs:
  using: composite
  steps:
    - name: Log image signing inputs
      shell: bash
      run: |
        {
          echo "### Image signing"

          echo "#### Image signing inputs"
          echo "| Key                 | Value |"
          echo "| ------------------- | ----- |"
          echo "| image | ${{ inputs.image }} |"
        } >> "$GITHUB_STEP_SUMMARY"

    - name: Install Cosign
      uses: sigstore/cosign-installer@7e8b541eb2e61bf99390e1afd4be13a184e9ebc5 # pin@v3.10.1

    - name: Extract metadata from image input
      id: set-signing-metadata
      shell: bash
      env:
        IMAGE: ${{ inputs.image }}
      run: |
        # Get digest from image inspection
        TARGET_IMAGE=$(docker inspect --format='{{index .RepoDigests 0}}' "$IMAGE")

        if [[ -z "$TARGET_IMAGE" ]]; then
          echo "::error title=Could not resolve repo digest::Could not resolve RepoDigest for $IMAGE. The image might not be pushed to a registry yet."
          exit 1
        fi

        # Extract pure digest
        IMAGE_DIGEST="${TARGET_IMAGE##*sha256:}"

        # Extract subject name from input
        # Strip potential digest to leave subject name and potential tag
        SUBJECT_NAME_TAG="${IMAGE%%@*}"

        # Strip tag to leave subject name
        SUBJECT_NAME="${SUBJECT_NAME_TAG%:*}"

        # Set outputs
        echo "image-digest=$IMAGE_DIGEST" >> "$GITHUB_OUTPUT"
        echo "subject-name=$SUBJECT_NAME" >> "$GITHUB_OUTPUT"

        # Set env. vars
        echo "$TARGET_IMAGE" >> "$GITHUB_ENV"

        {
          echo "#### Extracted image signing metadata"
          echo "| Key                 | Value |"
          echo "| ------------------- | ----- |"
          echo "| Target image | $TARGET_IMAGE |"
          echo "| Digest | $IMAGE_DIGEST |"
          echo "| Subject | $SUBJECT_NAME |"
        } >> "$GITHUB_STEP_SUMMARY"

    - name: Generate provenance metadata
      shell: bash
      run: |
        # Generate according to spec https://slsa.dev/spec/v1.0/provenance
        cat <<EOF > ./provenance.json
        {
          "_type": "https://slsa.dev/provenance/v1",
          "subject": [
            {
              "name": "${{ steps.set-signing-metadata.outputs.subject-name }}",
              "digest": {
                "sha256": "${{ steps.set-signing-metadata.outputs.image-digest }}"
              }
            }
          ],
          "buildDefinition": {
            "buildType": "https://github.com/github-actions/build",
            "externalParameters": {
              "image": "$TARGET_IMAGE",
              "commit": "${{ github.sha }}",
              "author": "${{ github.actor }}",
              "job": "${{ github.job }}",
              "repositoryOwnerId": "${{ github.repository_owner_id }}"
            }
          },
          "runDetails": {
            "builder": {
              "id": "${{ github.workflow_ref }}"
            },
            "metadata": {
              "invocationId": "${{ github.run_id }}",
              "startedOn": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
            }
          },
          "materials": [
            {
              "uri": "git+https://github.com/${{ github.repository }}.git",
              "digest": {
                "sha1": "${{ github.sha }}"
              }
            }
          ]
        }
        EOF

    - name: Sign and attest the image
      id: sign_and_attest
      shell: bash
      run: |
        echo "Signing image..."
        cosign sign --yes "$TARGET_IMAGE"

        echo "Attesting provenance..."
        cosign attest --yes --predicate ./provenance.json --type slsaprovenance1 "$TARGET_IMAGE"

    - name: Log security report
      if: steps.sign_and_attest.outcome == 'success'
      shell: bash
      run: |
        # echo "#### Cosign tree and verify report"

        # echo "##### Cosign artifact tree" >> "$GITHUB_STEP_SUMMARY"
        # echo '```console' >> "$GITHUB_STEP_SUMMARY"
        # cosign tree "$TARGET_IMAGE" >> "$GITHUB_STEP_SUMMARY"
        # echo '```' >> "$GITHUB_STEP_SUMMARY"

        # echo "##### Cosign verification check" >> "$GITHUB_STEP_SUMMARY"
        # echo "<details><summary>Click to view raw verification output</summary>" >> "$GITHUB_STEP_SUMMARY"
        # echo "" >> "$GITHUB_STEP_SUMMARY"
        # echo '```json' >> "$GITHUB_STEP_SUMMARY"
        # cosign verify "$TARGET_IMAGE" --certificate-identity-regexp ".*" --certificate-oidc-issuer-regexp ".*" >> "$GITHUB_STEP_SUMMARY" 2>&1
        # echo '```' >> "$GITHUB_STEP_SUMMARY"
        # echo "</details>" >> "$GITHUB_STEP_SUMMARY"

        {
          echo "#### Cosign tree and verify report"
          echo "##### Cosign artifact tree"
          echo '```console'
          cosign tree "$TARGET_IMAGE"
          echo '```'

          echo "##### Cosign verification check"
          echo "<details><summary>Click to view raw verification output</summary>"
          echo ""
          echo '```json'
          cosign verify "$TARGET_IMAGE" --certificate-identity-regexp ".*" --certificate-oidc-issuer-regexp ".*" 2>&1
          echo '```'
          echo "</details>"
          echo ""
        } >> "$GITHUB_STEP_SUMMARY"
