name: Trivy Vulnerability Scan
description: Composite action for Trivy vulnerability scanning
author: Digdir Platform Team

inputs:
  image-ref:
    description: Image reference to scan
    required: true
  library-ignore-unfixed:
    description: Ignore unfixed vulnerabilities in library scan
    default: "true"
    required: false
  library-severity:
    description: When to fail the scan with library vulnerabilities
    default: "HIGH,CRITICAL"
    required: false
  os-ignore-unfixed:
    description: Ignore unfixed vulnerabilities in OS scan
    default: "true"
    required: false
  os-severity:
    description: When to fail the scan with OS vulnerabilities
    default: "CRITICAL"
    required: false

runs:
  using: composite
  steps:
    - name: Run Trivy vulnerability library scan
      uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # pin@v0.33.1
      id: trivy-library
      env:
        TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db:2,public.ecr.aws/aquasecurity/trivy-db:2
        TRIVY_JAVA_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-java-db:1,public.ecr.aws/aquasecurity/trivy-java-db:1
      with:
        image-ref: ${{ inputs.image-ref }}
        scan-type: "image"
        format: "table"
        severity: "${{ inputs.library-severity }}"
        ignore-unfixed: ${{ inputs.library-ignore-unfixed }}
        exit-code: "1"

    - name: Run Trivy vulnerability OS scan
      uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # pin@v0.33.1
      id: trivy-os
      env:
        TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db:2,public.ecr.aws/aquasecurity/trivy-db:2
        TRIVY_JAVA_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-java-db:1,public.ecr.aws/aquasecurity/trivy-java-db:1
      with:
        image-ref: ${{ inputs.image-ref }}
        scan-type: "image"
        format: "table"
        severity: "${{ inputs.os-severity }}"
        ignore-unfixed: ${{ inputs.os-ignore-unfixed }}
        exit-code: "1"
