name: Trivy Vulnerability Scan
description: Composite action for Trivy vulnerability scanning
author: Digdir Platform Team

inputs:
  application-path:
    description: Path to application for Trivy scan (to detect .trivyignore)
    default: "./"
    required: false
  image-ref:
    description: Image reference to scan
    required: true
  library-disable-scan:
    description: Disable library scan
    default: "false"
    required: false
  library-ignore-unfixed:
    description: Ignore unfixed vulnerabilities in library scan
    default: "true"
    required: false
  library-severity:
    description: When to fail the scan with library vulnerabilities
    default: "HIGH,CRITICAL"
    required: false
  os-disable-scan:
    description: Disable OS scan
    default: "false"
    required: false
  os-ignore-unfixed:
    description: Ignore unfixed vulnerabilities in OS scan
    default: "true"
    required: false
  os-severity:
    description: When to fail the scan with OS vulnerabilities
    default: "CRITICAL"
    required: false

runs:
  using: composite
  steps:
    - name: Set trivyignore env if file exists
      id: set-trivyignore-path
      shell: bash
      env:
        APPLICATION_PATH: ${{ inputs.application-path }}
      run: |
        if [ -f "${{ env.APPLICATION_PATH }}.trivyignore" ]; then
          trivyignore_path=${{ env.APPLICATION_PATH }}.trivyignore
          echo "trivyignore-path=$trivyignore_path" >> "$GITHUB_OUTPUT"
          echo "- Trivy ignore path: $trivyignore_path" >> "$GITHUB_STEP_SUMMARY"
        fi

    - name: Run Trivy vulnerability library scan
      if: ${{ inputs.library-disable-scan != 'true' }}
      uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # pin@v0.33.1
      id: trivy-library
      env:
        TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db:2,public.ecr.aws/aquasecurity/trivy-db:2
        TRIVY_JAVA_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-java-db:1,public.ecr.aws/aquasecurity/trivy-java-db:1
      with:
        image-ref: ${{ inputs.image-ref }}
        scan-type: "image"
        format: "table"
        severity: "${{ inputs.library-severity }}"
        ignore-unfixed: ${{ inputs.library-ignore-unfixed }}
        trivyignores: ${{ steps.set-trivyignore-path.outputs.trivyignore-path }}
        exit-code: "1"

    - name: Run Trivy vulnerability OS scan
      if: ${{ inputs.os-disable-scan != 'true' }}
      uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # pin@v0.33.1
      id: trivy-os
      env:
        TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db:2,public.ecr.aws/aquasecurity/trivy-db:2
        TRIVY_JAVA_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-java-db:1,public.ecr.aws/aquasecurity/trivy-java-db:1
      with:
        image-ref: ${{ inputs.image-ref }}
        scan-type: "image"
        format: "table"
        severity: "${{ inputs.os-severity }}"
        ignore-unfixed: ${{ inputs.os-ignore-unfixed }}
        trivyignores: ${{ steps.set-trivyignore-path.outputs.trivyignore-path }}
        exit-code: "1"
