# https://github.com/DavidAnson/markdownlint/blob/v0.40.0/doc/md013.md
MD013:
  tables: false
  code_blocks: false

# https://github.com/DavidAnson/markdownlint/blob/v0.40.0/doc/md033.md
MD033: false

# https://github.com/DavidAnson/markdownlint/blob/v0.40.0/doc/md060.md
MD060: false
