name: Shai-Hulud malicious files scanner
description: Scans for malicious files related to Shai-Hulud supply chain attack
author: Digdir Platform Team

runs:
  using: composite
  steps:
    - name: SH scan
      shell: bash
      run: |
        #!/bin/bash
        set -euo pipefail

        echo "Installing dependencies with --ignore-scripts..."
        if [[ -f "yarn.lock" ]]; then
          yarn install --frozen-lockfile --ignore-scripts
        else
          npm install --ignore-scripts
        fi

        echo ""
        echo "Scanning..."

        FAILED=0

        echo ""
        echo "--- Wave 1 ---"

        MALICIOUS_POSTINSTALL=$(grep -rlE '"postinstall".*(shai|hulud|webhook\.site)' --include="package.json" . 2>/dev/null || true)
        if [[ -n "$MALICIOUS_POSTINSTALL" ]]; then
          echo "FAIL: malicious postinstall hook"
          echo "  Found in: $MALICIOUS_POSTINSTALL"
          FAILED=1
        else
          echo "OK: no malicious postinstall hook"
        fi

        if [[ -f .github/workflows/shai-hulud-workflow.yml ]]; then
          echo "FAIL: shai-hulud workflow file"
          FAILED=1
        else
          echo "OK: no shai-hulud workflow file"
        fi

        echo ""
        echo "--- Wave 2 ---"

        MALICIOUS_PREINSTALL=$(grep -rlE '"preinstall".*(setup_bun|bun_environment)' --include="package.json" . 2>/dev/null || true)
        if [[ -n "$MALICIOUS_PREINSTALL" ]]; then
          echo "FAIL: malicious preinstall hook"
          echo "  Found in: $MALICIOUS_PREINSTALL"
          FAILED=1
        else
          echo "OK: no malicious preinstall hook"
        fi

        LOADER_FILES=$(find . -type f \( -name "setup_bun.js" -o -name "bun_environment.js" \) 2>/dev/null || true)
        if [[ -n "$LOADER_FILES" ]]; then
          echo "FAIL: malicious loader file"
          echo "$LOADER_FILES" | while read -r file; do echo "  Found: $file"; done
          FAILED=1
        else
          echo "OK: no malicious loader file"
        fi

        OVERSIZED_JS=$(find . -type f -name "*.js" -size +10M 2>/dev/null || true)
        if [[ -n "$OVERSIZED_JS" ]]; then
          echo "FAIL: oversized js payload"
          echo "$OVERSIZED_JS" | while read -r file; do echo "  Found: $file"; done
          FAILED=1
        else
          echo "OK: no oversized js payload"
        fi

        DISCUSSION_WORKFLOWS=$(find . -type f \( -path "*/.github/workflows/discussion.yml" -o -path "*/.github/workflows/discussion.yaml" \) 2>/dev/null || true)
        if [[ -n "$DISCUSSION_WORKFLOWS" ]]; then
          echo "FAIL: discussion workflow file"
          echo "$DISCUSSION_WORKFLOWS" | while read -r file; do echo "  Found: $file"; done
          FAILED=1
        else
          echo "OK: no discussion workflow file"
        fi

        if [[ -d .dev-env || -d ~/.dev-env ]]; then
          echo "FAIL: runner persistence directory"
          [[ -d .dev-env ]] && echo "  Found: .dev-env"
          [[ -d ~/.dev-env ]] && echo "  Found: ~/.dev-env"
          FAILED=1
        else
          echo "OK: no runner persistence directory"
        fi

        EXFIL_FILES=$(find . -type f \( -name "truffleSecrets.json" -o -name "actionsSecrets.json" \) 2>/dev/null || true)
        if [[ -n "$EXFIL_FILES" ]]; then
          echo "FAIL: exfiltration data file"
          echo "$EXFIL_FILES" | while read -r file; do echo "  Found: $file"; done
          FAILED=1
        else
          echo "OK: no exfiltration data file"
        fi

        if [[ -d .truffler-cache || -d ~/.truffler-cache ]]; then
          echo "FAIL: trufflehog cache directory"
          [[ -d .truffler-cache ]] && echo "  Found: .truffler-cache"
          [[ -d ~/.truffler-cache ]] && echo "  Found: ~/.truffler-cache"
          FAILED=1
        else
          echo "OK: no trufflehog cache directory"
        fi

        echo ""
        echo "--- Common ---"

        WEBHOOK_REFS=$(grep -rlF "webhook.site" --include="*.js" --include="*.ts" . 2>/dev/null || true)
        if [[ -n "$WEBHOOK_REFS" ]]; then
          echo "FAIL: webhook.site reference"
          echo "  Found in: $WEBHOOK_REFS"
          FAILED=1
        else
          echo "OK: no webhook.site reference"
        fi

        TRUFFLEHOG_BINS=$(find . -type f -name "trufflehog" 2>/dev/null || true)
        if [[ -n "$TRUFFLEHOG_BINS" ]]; then
          echo "FAIL: trufflehog binary"
          echo "$TRUFFLEHOG_BINS" | while read -r file; do echo "  Found: $file"; done
          FAILED=1
        else
          echo "OK: no trufflehog binary"
        fi

        echo ""
        if [[ $FAILED -eq 1 ]]; then
          echo "FAILED: IOCs detected"
          exit 1
        else
          echo "PASSED: No IOCs detected"
        fi
