name: Shai-Hulud malicious files scanner
description: Scans for IOCs related to Shai-Hulud supply chain attack in NPM
author: Digdir Platform Team

inputs:
  install_method:
    description: "npm | yarn | ci | pnpm"
    required: true

runs:
  using: composite
  steps:
    - name: SH scan
      shell: bash
      env:
        INSTALL_METHOD: ${{ inputs.install_method }}
      run: |
        #!/bin/bash
        set -euo pipefail

        # Fill these arrays with known IOC from NPM attacks
        SUSPICIOUS_NODE_FILES=(
            "setup_bun.js"
            "bun_environment.js"
        )

        # Will only compute the hashes of the files in IOC_SHA256_FILES 
        # Then check if they match any of the hashes in IOC_SHA256 
        IOC_SHA256_FILES=(
            "bundle.js"
        )

        IOC_SHA256=(
            "46faab8ab153fae6e80e7cca38eab363075bb524edd79e42269217a083628f09"
        )

        # Check if INSTALL_METHOD is set and non-empty env variable 
        if [[ -z "${INSTALL_METHOD:-}" ]]; then
            echo "ERROR: INSTALL_METHOD needs to be npm | yarn | ci | pnpm" >&2
            exit 1
        fi

        NODE_MODULES_DIR="${NODE_MODULES_DIR:-node_modules}"

        get_sha256_filehash() {
        local f="$1"

        if [[ ! -r "$f" ]]; then
            echo "WARNING: Cannot read file for hashing: $f" >&2
            printf '\n' 
            return 0
        fi

        if command -v sha256sum >/dev/null 2>&1; then
            sha256sum "$f" | awk '{print $1}'
            return 0
        fi

        if command -v shasum >/dev/null 2>&1; then
            shasum -a 256 "$f" | awk '{print $1}'
            return 0
        fi

        echo "WARNING: No SHA256 tool found (sha256sum/shasum), skipping hashcheck for: $f" >&2
        printf '%s' ""
        return 0
        }

        function scan_files() {
            local base_dir="$1"

            [[ -d "$base_dir" ]] || {
                echo "WARNING: Directory not found (skipping file scanning): $base_dir" >&2
                return 0
            }

            local found=0
            local matches=""

            # Iterates the suspicious nodes files, and craches if any is found.
            for file in "${SUSPICIOUS_NODE_FILES[@]}"; do
                matches="$(find "$base_dir" -type f -name "$file" -print 2>/dev/null || true)"
                if [[ -n "$matches" ]]; then
                    found=1
                    echo "FAIL: Found suspicious NPM file: $file"
                    echo "$matches"
                fi 
            done 

            if [[ "$found" -eq 1 ]]; then
                return 1 
            fi 

            echo "OK: No suspicious NPM files found in $base_dir"
            return 0
        }

        function scan_for_hashes() {    
            local base_dir="$1"
            
            [[ -d "$base_dir" ]] || {
                echo "WARNING: Directory not found (skipping hash scan): $base_dir" >&2
                return 0
            }

            local found=0
            local matches=""
            local path=""
            local match_hash=""

            for file in "${IOC_SHA256_FILES[@]}"; do

                # Find all paths matching this filename
                matches="$(find "$base_dir" -type f -name "$file" -print 2>/dev/null || true)"
                
                # If none found, continue
                [[ -z "$matches" ]] && continue

                # Iterate each matched path 
                while IFS= read -r path; do
                    [[ -z "$path" ]] && continue

                    match_hash="$(get_sha256_filehash "$path")"
                    [[ -z "$match_hash" ]] && continue  # hashing failed, continue 
                    
                    for hash in "${IOC_SHA256[@]}"; do
                        if [[ "$match_hash" == "$hash" ]]; then
                        found=1
                        echo "FAIL: SHA256 IOC match"
                        echo "  file:   $file"
                        echo "  path:   $path"
                        echo "  sha256: $match_hash"
                        echo
                        fi
                    done
                done <<< "$matches"
            done

            if [[ "$found" -eq 1 ]]; then
                return 1
            fi

            echo "OK: No IOC SHA256 hash found in node_modules"
        }


        if [[ "$INSTALL_METHOD" == "npm" ]]; then
            npm install --ignore-scripts 
            scan_files "$NODE_MODULES_DIR"
            scan_for_hashes "$NODE_MODULES_DIR"

        elif [[ "$INSTALL_METHOD" == "yarn" ]]; then
            yarn install --frozen-lockfile --ignore-scripts 
            scan_files "$NODE_MODULES_DIR"
            scan_for_hashes "$NODE_MODULES_DIR"

        elif [[ "$INSTALL_METHOD" == "ci" ]]; then
            npm ci --ignore-scripts
            scan_files "$NODE_MODULES_DIR"
            scan_for_hashes "$NODE_MODULES_DIR"
        
        elif [[ "$INSTALL_METHOD" == "pnpm" ]]; then
            pnpm install
            scan_files "$NODE_MODULES_DIR"
            scan_for_hashes "$NODE_MODULES_DIR"

        else
            echo "ERROR: Unsupported INSTALL_METHOD: $INSTALL_METHOD (use: npm | yarn | ci)" >&2
            exit 2

        fi    




