name: Write JSON to step summary
description: |
  Composite action to write JSON content to the step summary. The action accepts
  a JSON input and an optional title. This is normally used to write GitHub
  Actions inputs to the step summary
author: Digdir Platform Team

inputs:
  title:
    description: The Markdown heading for the step summary table
    required: false
    default: Inputs
  json-payload:
    description: JSON payload to parse and write to the step summary
    required: true

runs:
  using: composite
  steps:
    - name: Write JSON to step summary
      shell: bash
      run: |
        {
          echo "#### ${{ inputs.title }}"
          echo "| Input | Value |"
          echo "| ----- | ----- |"
          echo '${{ inputs.json-payload }}' | jq -r ' to_entries[]? |
            if (.key | test("token|password|secret|key"; "i")) then
              "| \(.key) | `***` |"
            else
              "| \(.key) | `\(.value)` |"
            end
          '
        } >> $GITHUB_STEP_SUMMARY
