name: Syntax check workflows files (actionlint)
run-name: "actionlint"
on: [push]

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: "Run actionlint"
        uses: felleslosninger/github-actions/run-actionlint@d7888fecafbf48e5845c8a0c76389f71c517ee6d # pin@v0.8.0
