name: Build and publish Docker image

on:
  workflow_call:
    inputs:
      image-name:
        description: Name of Docker image
        required: false
        type: string
      image-pack:
        description: Paketo builder image to use. See https://paketo.io/docs/reference/builders-reference/ for choices
        default: builder-noble-java-tiny
        required: false
        type: string
      image-pack-tag:
        description: "Docker image pack version tag. Earlier pinned to 0.0.440 due to lifecycle 0.21.2 regression (see: paketo-buildpacks/builder-noble-java-tiny#191). Now fixed: https://github.com/paketo-buildpacks/builder-noble-java-tiny/issues/191#issuecomment-3897508140"
        default: "latest"
        required: false
        type: string
      image-signing:
        description: Flag to toggle image signing on/off - default off
        default: true
        required: false
        type: boolean
      image-tag:
        description: Custom image tag, if not provided a tag will be auto-generated
        default: ""
        required: false
        type: string
      java-version:
        description: Main version of java
        default: "11"
        required: false
        type: string
      java-distribution:
        description: Java distribution to use
        default: "liberica"
        required: false
        type: string
      slack-channel-id:
        description: Team channel id
        default: ""
        required: false
        type: string
      application-path:
        default: "./"
        required: false
        type: string
      cache-path:
        default: "**/pom.xml"
        required: false
        type: string
      update-versions:
        default: "true"
        required: false
        type: string
      setup-npm-auth:
        description: Configure private NPM registry authentication
        default: false
        required: false
        type: boolean
      application-type:
        default: "spring-boot"
        required: false
        type: string
      add-git-package-token:
        required: false
        type: boolean
      native:
        required: false
        type: boolean
        default: false
      lifecycle:
        required: false
        default: "deployment"
        type: string
      cr-type:
        required: false
        default: "acr"
        type: string
      module-name:
        description: Module name to build (for multi-module projects)
        required: false
        type: string
      trivy-library-disable-scan:
        description: Disable Trivy library scan
        type: boolean
        required: false
        default: false
      trivy-library-ignore-unfixed:
        description: Ignore unfixed vulnerabilities in Trivy library scan
        type: boolean
        required: false
        default: true
      trivy-library-severity:
        description: When to fail the scan with Trivy library vulnerabilities
        type: string
        required: false
        default: 'HIGH,CRITICAL'
      trivy-os-disable-scan:
        description: Disable Trivy OS scan
        type: boolean
        required: false
        default: false
      trivy-os-ignore-unfixed:
        description: Ignore unfixed vulnerabilities in Trivy OS scan
        type: boolean
        required: false
        default: true
      trivy-os-severity:
        description: When to fail the scan with Trivy OS vulnerabilities
        type: string
        required: false
        default: 'CRITICAL'
      trivy-version:
        description: Version of Trivy to use for scanning
        type: string
        required: false
        default: ''

    outputs:
      image-version:
        description: "Docker image version"
        value: ${{ jobs.run-spring-boot-build.outputs.image-version || jobs.run-quarkus-build.outputs.image-version || jobs.run-docker-build.outputs.image-version }}
      image-digest:
        description: "Docker image SHA256 digest"
        value: ${{ jobs.run-spring-boot-build.outputs.image-digest || jobs.run-quarkus-build.outputs.image-digest || jobs.run-docker-build.outputs.image-digest }}

jobs:
  inputs-to-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Write inputs to summary
        uses: felleslosninger/github-workflows/.github/actions/json-to-summary@main
        with:
          json-payload: ${{ toJson(inputs) }}

  input-checks:
    runs-on: ubuntu-latest
    outputs:
      container-registry: ${{ steps.set-container-registry.outputs.container-registry }}
      sp-container-registry-client-id: ${{ steps.set-container-registry.outputs.sp-container-registry-client-id }}

    steps:
      - name: Check for supported application-type
        id: application-type-check
        run: |
          if [[ ${{ inputs.application-type }} != "spring-boot" && ${{ inputs.application-type }} != "quarkus" && ${{ inputs.application-type }} != "docker" ]]; then
            echo "Invalid application type. Supported types are: \`spring-boot\`, \`quarkus\` and \`docker\`" >> "$GITHUB_STEP_SUMMARY"
            exit 1
          fi

      - name: Set container registry
        id: set-container-registry
        run: |
          if [[ "${{ inputs.cr-type }}" == "ghcr" ]]; then
            echo "container-registry=ghcr.io" >> "$GITHUB_OUTPUT"
          elif [[ "${{ inputs.lifecycle }}" == "deployment" ]]; then
            echo "sp-container-registry-client-id=AZURE_CLIENT_ID" >> "$GITHUB_OUTPUT"
            echo "container-registry=${{ vars.CR_DEPLOYMENT_URL }}" >> "$GITHUB_OUTPUT"
          elif [[ "${{ inputs.lifecycle }}" == "development" ]]; then
            echo "sp-container-registry-client-id=CR_DEV_USERNAME" >> "$GITHUB_OUTPUT"
            echo "container-registry=${{ vars.CR_DEV_URL }}" >> "$GITHUB_OUTPUT"
          else
            echo "Invalid lifecycle type. Supported types are: \`deployment\`, and \`development\`" >> "$GITHUB_STEP_SUMMARY"
          fi

  run-spring-boot-build:
    needs: input-checks
    if: inputs.application-type == 'spring-boot'
    uses: felleslosninger/github-workflows/.github/workflows/ci-spring-boot-build-publish-image.yml@main
    with:
      image-name: ${{ inputs.image-name }}
      image-pack: ${{ inputs.image-pack }}
      image-pack-tag: ${{ inputs.image-pack-tag }}
      image-signing: ${{ inputs.image-signing }}
      image-tag: ${{ inputs.image-tag }}
      java-version: ${{ inputs.java-version }}
      java-distribution: ${{ inputs.java-distribution }}
      slack-channel-id: ${{ inputs.slack-channel-id }}
      application-path: ${{ inputs.application-path }}
      cache-path: ${{ inputs.cache-path }}
      update-versions: ${{ inputs.update-versions }}
      container-registry: ${{ needs.input-checks.outputs.container-registry }}
      sp-container-registry-client-id: ${{ needs.input-checks.outputs.sp-container-registry-client-id }}
      setup-npm-auth: ${{ inputs.setup-npm-auth }}
      module-name: ${{ inputs.module-name }}
      trivy-library-disable-scan: ${{ inputs.trivy-library-disable-scan }}
      trivy-library-ignore-unfixed: ${{ inputs.trivy-library-ignore-unfixed }}
      trivy-library-severity: ${{ inputs.trivy-library-severity }}
      trivy-os-disable-scan: ${{ inputs.trivy-os-disable-scan }}
      trivy-os-ignore-unfixed: ${{ inputs.trivy-os-ignore-unfixed }}
      trivy-os-severity: ${{ inputs.trivy-os-severity }}
      trivy-version: ${{ inputs.trivy-version }}
    secrets: inherit

  run-quarkus-build:
    needs: input-checks
    if: inputs.application-type == 'quarkus'
    uses: felleslosninger/github-workflows/.github/workflows/ci-quarkus-build-publish-image.yml@main
    with:
      image-name: ${{ inputs.image-name }}
      image-pack: ${{ inputs.image-pack }}
      image-pack-tag: ${{ inputs.image-pack-tag }}
      image-signing: ${{ inputs.image-signing }}
      java-version: ${{ inputs.java-version }}
      java-distribution: ${{ inputs.java-distribution }}
      slack-channel-id: ${{ inputs.slack-channel-id }}
      cache-path: ${{ inputs.cache-path }}
      native: ${{ inputs.native }}
      container-registry: ${{ needs.input-checks.outputs.container-registry }}
      sp-container-registry-client-id: ${{ needs.input-checks.outputs.sp-container-registry-client-id }}
      trivy-library-disable-scan: ${{ inputs.trivy-library-disable-scan }}
      trivy-library-ignore-unfixed: ${{ inputs.trivy-library-ignore-unfixed }}
      trivy-library-severity: ${{ inputs.trivy-library-severity }}
      trivy-os-disable-scan: ${{ inputs.trivy-os-disable-scan }}
      trivy-os-ignore-unfixed: ${{ inputs.trivy-os-ignore-unfixed }}
      trivy-os-severity: ${{ inputs.trivy-os-severity }}
      trivy-version: ${{ inputs.trivy-version }}
    secrets: inherit

  run-docker-build:
    needs: input-checks
    if: inputs.application-type == 'docker'
    uses: felleslosninger/github-workflows/.github/workflows/ci-docker-build-publish-image.yml@main
    with:
      image-name: ${{ inputs.image-name }}
      image-signing: ${{ inputs.image-signing }}
      slack-channel-id: ${{ inputs.slack-channel-id }}
      application-path: ${{ inputs.application-path }}
      add-git-package-token: ${{ inputs.add-git-package-token }}
      container-registry: ${{ needs.input-checks.outputs.container-registry }}
      sp-container-registry-client-id: ${{ needs.input-checks.outputs.sp-container-registry-client-id }}
      trivy-library-disable-scan: ${{ inputs.trivy-library-disable-scan }}
      trivy-library-ignore-unfixed: ${{ inputs.trivy-library-ignore-unfixed }}
      trivy-library-severity: ${{ inputs.trivy-library-severity }}
      trivy-os-disable-scan: ${{ inputs.trivy-os-disable-scan }}
      trivy-os-ignore-unfixed: ${{ inputs.trivy-os-ignore-unfixed }}
      trivy-os-severity: ${{ inputs.trivy-os-severity }}
      trivy-version: ${{ inputs.trivy-version }}
    secrets: inherit
