# This is a reusable GitHub workflow designed to check for changes in the .trivyignore file
# from previous commits. The sole purpose is to report any added (suppressed) or removed (un-suppressed)
# CVE changes to InfluxDB and be a part of our vulnerabilities control.

# author: Digdir Platform Team

name: Check for CVE suppression changes

on:
  workflow_call:
jobs:
  check-for-cve-suppression-changes:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 #ping@v4.2.0
        with:
          fetch-depth: 0

      - name: Install InfluxDB Client
        run: |
          npm install @influxdata/influxdb-client
          npm install @actions/core

      - name: Check for CVE suppression changes in trivyignore
        id: new-cve-suppressions
        if: ${{ hashFiles('./.trivyignore') != '' }}
        env:
          COMMIT_HASH_BEFORE: ${{ github.event.before }}
          COMMIT_HASH_AFTER: ${{ github.event.after }}
        run: |
          # File with CVEs
          TRIVYIGNORE_FILE=.trivyignore

          # File with git diff results
          GIT_DIFF_RAW_FILE=trivy-git-diff.txt

          # CVE format pattern: CVE-[0-9]{4}-[0-9]{1,}
          # With expected leading prefix: '+' for added and '-' for removed
          regex_pattern="^([+]|[-])(CVE|cve)-[0-9]{4}-[0-9]{1,}$"

          git diff --ignore-all-space ${{ env.COMMIT_HASH_BEFORE }}..${{ env.COMMIT_HASH_AFTER }} -- $TRIVYIGNORE_FILE > $GIT_DIFF_RAW_FILE

          suppressions_with_delimiter=""
          while read -r diff_string
          do
            suppression=$(cut -d' ' -f 1 <<< "$diff_string")
            if [[ $suppression =~ $regex_pattern ]]; then
              suppressions_with_delimiter+="$suppression,"
            fi
          done < <(grep '' $GIT_DIFF_RAW_FILE)
          echo "suppressions=$suppressions_with_delimiter" >> "$GITHUB_OUTPUT"

      - name: Write CVE suppressions to InfluxDB
        if: ${{ steps.new-cve-suppressions.outputs.suppressions != '' }}
        id: write-supressions-to-influxdb
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea #pin@v7.0.1
        env:
          INFLUXDB_TOKEN: ${{ secrets.INFLUXDB_TOKEN_CVE }}
          INFLUXDB_URL: "https://westeurope-1.azure.cloud2.influxdata.com"
          SUPPRESSIONS: ${{ steps.new-cve-suppressions.outputs.suppressions }}
          BUCKET: "cve"
        with:
          script: |
            const { InfluxDB, Point } = require("@influxdata/influxdb-client")

            const {
              INFLUXDB_TOKEN,
              INFLUXDB_URL,
              BUCKET,
            } = process.env

            const client = new InfluxDB({
              url: INFLUXDB_URL,
              token: INFLUXDB_TOKEN,
            }).getWriteApi('', BUCKET, "ns")

            const suppressionsAsString = '${{ env.SUPPRESSIONS }}'

            const delimiter = ','

            const suppressionsAsStringArray = toStringArray(suppressionsAsString, delimiter)

            const suppressions = [...suppressionsAsStringArray]

            for (suppression of suppressions) {
              const suppressionWithoutPrefix = `${suppression.substring(1)}`
              const event_type = getSuppressedOrUnSuppressedEventType(suppression)
              const point = new Point("cve")
                .tag("repository", "${{ github.repository }}")
                .tag("application", "${{ github.event.repository.name }}")
                .stringField("commit_hash", "${{ github.event.head_commit.id }}")
                .stringField("cve", `${suppressionWithoutPrefix}`)
                .stringField("event", `${event_type}`)

              core.info(`Data: ${JSON.stringify(point)}`)
              client.writePoint(point)
            }

            function toStringArray(theString, delimiter) {
              let data = []
              for (let string of theString.split(delimiter)) {
                if (string !== '') {
                  data.push(string.trim().replace(/,$/, ""))
                }
              }
              return data
            }

            function getSuppressedOrUnSuppressedEventType(suppression) {
              let event_type = ''
              if (suppression !== "" && !suppression.startsWith("#")) {
                if (suppression.startsWith("+")) {
                  event_type = "suppressed"
                } else if (suppression.startsWith("-")) {
                  event_type = "un-suppressed"
                }
              }
              return event_type
            }

            // Flush pending writes and close client.
            client.close().then(() => {
              core.info("CVE changes successfully written to InfluxDB")
            })
