name: Release to github packages

on:
  workflow_call:
    inputs:
      java-version:
        description: Main version of java
        default: "21"
        required: false
        type: string
      sbom-path:
        description: Target directory for SBOM generation
        default: ./target/
        required: false
        type: string
      profile:
        description: Maven profile to use
        required: false
        type: string
      artifact-name:
        required: false
        type: string
      fetch-depth:
        description: Fetch depth
        default: 1
        required: false
        type: number
      cache-path:
        default: "**/pom.xml"
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ inputs.fetch-depth }}

      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # pin@v4.7.0
        with:
          distribution: "liberica"
          java-version: ${{ inputs.java-version }}
          cache: maven
          cache-dependency-path: ${{ inputs.cache-path }}
          
      - name: Set m2 settings to read organization packages
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>github</id><username>${{ secrets.GH_PACKAGES_READ_USER }}</username><password>${{ secrets.GH_PACKAGES_READ_PAT }}</password></server></servers></settings>" > ~/.m2/settings.xml

      - name: Decrypt GPG Key
        run: |
          echo "${{ secrets.EFM_GPG_PRIVATE_KEY }}" | gpg --batch --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.EFM_GPG_PRIVATE_KEY }}

      - name: Overwrite m2 settings to publish libs
        run: |
          echo "<settings><servers><server><id>github</id><username>${{ github.actor }}</username><password>${{ github.token }}</password></server><server><id>ossrh</id><username>${{ secrets.EFM_OSSRH_TOKEN_USERNAME }}</username><password>${{ secrets.EFM_OSSRH_TOKEN }}</password></server></servers></settings>" > ~/.m2/settings.xml

      - name: Deploy package
        run: |
          if [ -n "${{ inputs.profile }}" ]; then
            mvn -B deploy -P"${{ inputs.profile }}" "-Dgpg.passphrase=${{ secrets.EFM_GPG_PASSPHRASE }}"
          else
            mvn -B deploy "-Dgpg.passphrase=${{ secrets.EFM_GPG_PASSPHRASE }}"
          fi

      - name: Set artifact id
        id: set-artifact-id
        run: |
          echo "artifact-id=${{ inputs.artifact-name }}-${{ github.run_number }}-${{ github.run_attempt }}.spdx" >> "$GITHUB_OUTPUT"

      - uses: anchore/sbom-action@v0
        with:
          path: ${{ inputs.sbom-path }}
          artifact-name: ${{ steps.set-artifact-id.outputs.artifact-id }}
