# Workflow Name: Maven build java (PR)
#
# PS! This workflow is deprecated, and should not be used for new projects. The
# ci-pr-checks.yml workflow have been updated to support all functionality of
# this workflow, and should be used instead. This workflow will remain
# available for existing projects that have not yet migrated to the
# ci-pr-checks.yml workflow, but will be removed in the future. Please reach
# out to the Digdir Platform team if you have any questions or need assistance
# with migration.
#
# Owner: Digdir Platform team / Digdir development teams
#
# Purpose:
#   This workflow is designed to perform a Maven build of a Java application,
#   run a Trivy vulnerability 'fs' scan to detect vulnerabilities fast in a PR.
#   It runs 2 jobs in parallel: one to verify the pull request title, and
#   another to perform the build and scan.
#
#   Flow:
#     1. Checkout repository
#     2. Set up JDK
#     3. Build with Maven (supports lifecycle phases: test, package, verify,
#        install)
#     4. Run Trivy vulnerability scanner ('fs' scan)
#
# Trigger:
#   Triggered by workflow calls (workflow_call)
#
# Inputs:
#   See input section
#
# Outputs:
#   None
#

name: Maven build java (PR)

permissions: {}

on:
  workflow_call:
    inputs:
      java-version:
        description: Main version of java
        default: "11"
        required: false
        type: string
      java-distribution:
        description: Java distribution to use
        default: "liberica"
        required: false
        type: string
      application-path:
        description: Path to the application directory to scan with Trivy, relative to the repository root
        default: "./"
        required: false
        type: string
      cache-path:
        description: Path to cache dependencies, relative to the repository root
        default: "**/pom.xml"
        required: false
        type: string
      maven-lifecycle:
        description: 'Maven lifecycle phase (test, package, verify, install)'
        type: string
        required: false
        default: 'test'
      trivy-library-disable-scan:
        description: Disable Trivy library scan
        type: boolean
        required: false
        default: false
      trivy-library-ignore-unfixed:
        description: Ignore unfixed vulnerabilities in Trivy library scan
        type: boolean
        required: false
        default: true
      trivy-library-severity:
        description: When to fail the scan with Trivy library vulnerabilities
        type: string
        required: false
        default: 'HIGH,CRITICAL'
      trivy-version:
        description: Version of Trivy to use for scanning
        type: string
        required: false
        default: ''

jobs:
  verify-pull-request-title:
    if: ${{ github.event_name == 'pull_request'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # pin@v9.0.0
        with:
          script: |
            const REGEX = new RegExp("^[^…]+$");  // Title must match this regex
            const MIN_LENGTH = 10;                 // Min length of the title
            const MAX_LENGTH = 100;                // Max length of the title (-1 is no max)
            const ALLOWED_PREFIXES = ['Bump','ID-','MIN-','PBLEID-','MP-','KRR-','PF-','AOS-','SP-','EIN-','EUW-','MOVE-'];          // Title must start with one of these prefixes
            const PREFIX_CASE_SENSITIVE = false;  // Whether the prefix is case sensitive

            const validateTitlePrefix = (title, prefix) =>
              PREFIX_CASE_SENSITIVE
                ? title.startsWith(prefix)
                : title.toLowerCase().startsWith(prefix.toLowerCase());

            const { title } = context.payload.pull_request;
            if (!REGEX.test(title)) {
              core.setFailed(
                `Pull Request title "${title}" failed to match regex - ${REGEX}`
              );
              return;
            }

            if (title.length < MIN_LENGTH) {
              core.setFailed(
                `Pull Request title "${title}" is smaller than the minimum length - ${MIN_LENGTH}`
              );
              return;
            }

            if (MAX_LENGTH > 0 && title.length > MAX_LENGTH) {
              core.setFailed(
                `Pull Request title "${title}" is greater than the maximum length - ${MAX_LENGTH}`
              );
              return;
            }

            core.info(`Allowed Prefixes: ${ALLOWED_PREFIXES}`);
            if (
              ALLOWED_PREFIXES.length &&
              !ALLOWED_PREFIXES.some((prefix) => validateTitlePrefix(title, prefix))
            ) {
              core.setFailed(
                `Pull Request title "${title}" did not start with any of the required prefixes - ${ALLOWED_PREFIXES}`
              );
              return;
            }

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v6.0.2

      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # pin@v5.2.0
        with:
          distribution: "${{ inputs.java-distribution }}"
          java-version: ${{ inputs.java-version }}
          cache: maven
          cache-dependency-path: ${{ inputs.cache-path }}
          server-id: github
          server-username: MAVEN_USER
          server-password: MAVEN_PASSWORD

      - name: Run mvn ${{ inputs.maven-lifecycle }}
        env:
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: |
          LIFECYCLE="${{ inputs.maven-lifecycle }}"
          case "$LIFECYCLE" in
            test|package|verify|install)
              mvn -B "$LIFECYCLE"
              ;;
            *)
              echo "Invalid Maven lifecycle: $LIFECYCLE"
              exit 1
              ;;
          esac

      - name: Run Trivy vulnerability scanner
        uses: felleslosninger/github-workflows/.github/actions/trivy-scan@main
        with:
          scan-type: "fs"
          application-path: ${{ inputs.application-path }}
          library-disable-scan: ${{ inputs.trivy-library-disable-scan }}
          library-ignore-unfixed: ${{ inputs.trivy-library-ignore-unfixed }}
          library-severity: ${{ inputs.trivy-library-severity }}
          trivy-version: ${{ inputs.trivy-version }}
