name: Release to github packages

on:
  workflow_call:
    inputs:
      java-version:
        description: Main version of java
        default: '11'
        required: false
        type: string
      java-distribution:
        description: Java distribution to use
        default: "liberica"
        required: false
        type: string
      sbom-path:
        description: Target directory for SBOM generation
        default: ./target/
        required: false
        type: string
      package-version:
        description: Version to use for maven package
        default: ""
        required: false
        type: string
      deployment-repository:
        description: Set deployment repo
        default: ""
        required: false
        type: string
      cache-path:
        default: "**/pom.xml"
        required: false
        type: string
      application-path:
        default: "./"
        required: false
        type: string
      trivy-library-disable-scan:
        description: Disable Trivy library scan
        type: boolean
        required: false
        default: false
      trivy-library-ignore-unfixed:
        description: Ignore unfixed vulnerabilities in Trivy library scan
        type: boolean
        required: false
        default: true
      trivy-library-severity:
        description: When to fail the scan with Trivy library vulnerabilities
        type: string
        required: false
        default: 'HIGH,CRITICAL'
      trivy-library-hide-progress:
        description: Hide progress output for Trivy library scan
        type: boolean
        required: false
        default: true
      trivy-version:
        description: Version of Trivy to use for scanning
        type: string
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # pin@v5.0.0
      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # pin@v5.0.0
        with:
          distribution: "${{ inputs.java-distribution }}"
          java-version: ${{ inputs.java-version }}
          cache: maven
          cache-dependency-path: ${{ inputs.cache-path }}

      - name: Run Trivy vulnerability scanner
        uses: felleslosninger/github-workflows/.github/actions/trivy-scan@main
        with:
          scan-type: "fs"
          application-path: ${{ inputs.application-path }}
          library-disable-scan: ${{ inputs.trivy-library-disable-scan }}
          library-ignore-unfixed: ${{ inputs.trivy-library-ignore-unfixed }}
          library-severity: ${{ inputs.trivy-library-severity }}
          library-hide-progress: ${{ inputs.trivy-library-hide-progress }}
          trivy-version: ${{ inputs.trivy-version }}

      - name: Set m2 settings
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>github</id><username>${{ github.actor }}</username><password>${{ github.token }}</password></server></servers></settings>" > ~/.m2/settings.xml

      - name: Set version
        run: |
          if [ "${{ inputs.package-version }}" != "" ]; then
            mvn versions:set -B -DnewVersion="${{ inputs.package-version }}"
            echo "- \`mvn versions\` was executed" >> "$GITHUB_STEP_SUMMARY"
          else
            echo "- \`mvn versions\` was not executed" >> "$GITHUB_STEP_SUMMARY"
          fi

      - name: Deploy to maven repository
        run: |
          if [ "${{ inputs.deployment-repository }}" != "" ]; then
            mvn -B deploy -DaltDeploymentRepository="github::default::https://maven.pkg.github.com/${{ inputs.deployment-repository }}"
            echo "- \`mvn versions\` was executed" >> "$GITHUB_STEP_SUMMARY"
          else
            mvn -B deploy
          fi

      - uses: anchore/sbom-action@57aae528053a48a3f6235f2d9461b05fbcb7366d # pin@v0.23.1
        with:
          path: ${{ inputs.sbom-path }}
