name: Release to github packages

on:
  workflow_call:
    inputs:
      java-version:
        description: Main version of java
        default: '11'
        required: false
        type: string
      sbom-path:
        description: Target directory for SBOM generation
        default: ./target/
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'liberica'
      - name: Publish package
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: anchore/sbom-action@v0
        with:
          path: ${{ inputs.sbom-path }}
