name: Release to github packages

on:
  workflow_call:
    inputs:
      java-version:
        description: Main version of java
        default: '11'
        required: false
        type: string
      sbom-path:
        description: Target directory for SBOM generation
        default: ./target/
        required: false
        type: string

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: ${{ inputs.java-version }}

      - uses: s4u/maven-settings-action@v2.8.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          servers: |
            [{
            "id": "github",
            "username": "${GITHUB_ACTOR}",
            "password": "${env.GITHUB_TOKEN}"
            }]
          settings: |
            <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                      xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                          http://maven.apache.org/xsd/settings-1.0.0.xsd">
              <activeProfiles>
                <activeProfile>github</activeProfile>
              </activeProfiles>
              <profiles>
                <profile>
                  <id>github</id>
                  <repositories>
                    <repository>
                      <id>github</id>
                      <url>https://maven.pkg.github.com/felleslosninger/*</url>
                      <snapshots>
                        <enabled>true</enabled>
                      </snapshots>
                    </repository>
                  </repositories>
                </profile>
              </profiles>
            </settings>

      - name: Deploy to Github Package Registry
        run: |                  
          REPO="github::default::https://maven.pkg.github.com/felleslosninger"
          mvn -B deploy -DaltDeploymentRepository="${REPO}"

      - uses: anchore/sbom-action@v0
        with:
          path: ${{ inputs.sbom-path }}