name: Release to github packages

on:
  workflow_call:
    inputs:
      java-version:
        description: Main version of java
        default: '11'
        required: false
        type: string
      sbom-path:
        description: Target directory for SBOM generation
        default: ./target/
        required: false
        type: string
      package-version:
        description: Version to use for maven package
        default: ""
        required: false
        type: string
      deployment-repository:
        description: Set deployment repo
        default: ""
        required: false
        type: string
      cache-path:
        default: "**/pom.xml"
        required: false
        type: string
      application-path:
        default: "./"
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # pin@v5.0.0
      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # pin@v4.7.0
        with:
          distribution: "liberica"
          java-version: ${{ inputs.java-version }}
          cache: maven
          cache-dependency-path: ${{ inputs.cache-path }}

      - name: Set m2 settings
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>github</id><username>${{ github.actor }}</username><password>${{ github.token }}</password></server></servers></settings>" > ~/.m2/settings.xml

      - name: Set version
        run: |
          if [ "${{ inputs.package-version }}" != "" ]; then
            mvn versions:set -B -DnewVersion="${{ inputs.package-version }}"
            echo "- \`mvn versions\` was executed" >> "$GITHUB_STEP_SUMMARY"
          else
            echo "- \`mvn versions\` was not executed" >> "$GITHUB_STEP_SUMMARY"
          fi

      - name: Deploy to maven repository
        run: |
          if [ "${{ inputs.deployment-repository }}" != "" ]; then
            mvn -B deploy -DaltDeploymentRepository="github::default::https://maven.pkg.github.com/${{ inputs.deployment-repository }}"
            echo "- \`mvn versions\` was executed" >> "$GITHUB_STEP_SUMMARY"
          else
            mvn -B deploy
          fi

      - name: Set trivyignore env if file exists
        id: set-trivyignore-path
        run: |
          if [ -f "${{ inputs.application-path }}.trivyignore" ]; then
            trivyignore_path=${{ inputs.application-path }}.trivyignore
            echo "trivyignore-path=$trivyignore_path" >> "$GITHUB_OUTPUT"
            echo "- Trivy ignore path: $trivyignore_path" >> "$GITHUB_STEP_SUMMARY"
          fi

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0 # pin@v0.29.0
        id: trivy-maven
        env:
          TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db:2,public.ecr.aws/aquasecurity/trivy-db:2
          TRIVY_JAVA_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-java-db:1,public.ecr.aws/aquasecurity/trivy-java-db:1
        with:
          scan-type: 'fs'
          scan-ref: '${{ inputs.application-path }}'
          exit-code: "1"
          severity: "CRITICAL,HIGH"
          trivyignores: ${{ steps.set-trivyignore-path.outputs.trivyignore-path }}

      - uses: anchore/sbom-action@f325610c9f50a54015d37c8d16cb3b0e2c8f4de0 # pin@v0.18.0
        with:
          path: ${{ inputs.sbom-path }}
