name: Release to github packages

on:
  workflow_call:
    inputs:
      java-version:
        description: Main version of java
        default: '11'
        required: false
        type: string
    secrets:
      github-user:
        description: User for github
        required: true
      github-token:
        description: Token for github
        required: true
      sbom-path:
        description: Target directory for SBOM generation
        default: ./target/
        required: false
        type: string

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: ${{ inputs.java-version }}

      - uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: |
            [{
            "id": "github",
            "username": "${{ secrets.github-user }}",
            "password": "${{ secrets.github-token }}"
            }]

      - uses: anchore/sbom-action@v0
        with:
          path: ${{ inputs.sbom-path }}
        