# Workflow Name: Quarkus container scan
#
# Owner: Digdir Platform team
#
# Purpose:
#   This is part of the golden path for PRs towards main branch. The workflow
#   should not normally be used directly, but called from the ci-pr-checks
#   workflow, which checks certain things before calling this workflow with the
#   correct parameters. This workflow will build a temporary Quarkus image
#   based on the 'native' input parameter, which determines whether to build a
#   JVM or GraalVM native image. The workflow will use Pack and Paketo
#.  buildpacks for building the image, and the specific builder image can be
#   configured through inputs. After building the image, the workflow will run
#.  Trivy vulnerability scans.
#
#   Flow:
#     1. Set image metadata (name and tag)
#     2. Checkout repository
#     3. Set up JDK
#     4. Build Quarkus image using Paketo buildpacks. The image will either be a
#        JVM or GraalVM native image based on the 'native' input parameter
#     5. Run Trivy vulnerability scan on the built image
#
# Trigger:
#   Triggered by workflow calls (workflow_call)
#
# Inputs:
#   See input section
#
# Outputs:
#   None
#

name: Quarkus container scan

permissions: {}

on:
  workflow_call:
    inputs:
      image-name:
        description: Name of Docker image
        required: false
        type: string
      image-pack:
        description: Paketo builder image to use. See https://paketo.io/docs/reference/builders-reference/ for choices
        default: builder-noble-java-tiny
        required: false
        type: string
      image-pack-tag:
        description: Docker image pack version tag
        default: "latest"
        required: false
        type: string
      java-version:
        description: Main version of java
        default: "11"
        required: false
        type: string
      java-distribution:
        description: Java distribution to use
        default: "liberica"
        required: false
        type: string
      cache-path:
        description: Path to cache dependencies, relative to the repository root
        default: "**/pom.xml"
        required: false
        type: string
      native:
        description: Build native image
        required: false
        type: boolean
        default: false
      application-path:
        description: Path to the application directory to scan with Trivy, relative to the repository root
        default: "./"
        required: false
        type: string
      trivy-library-disable-scan:
        description: Disable Trivy library scan
        type: boolean
        required: false
        default: false
      trivy-library-ignore-unfixed:
        description: Ignore unfixed vulnerabilities in Trivy library scan
        type: boolean
        required: false
        default: true
      trivy-library-severity:
        description: When to fail the scan with Trivy library vulnerabilities
        type: string
        required: false
        default: 'HIGH,CRITICAL'
      trivy-os-disable-scan:
        description: Disable Trivy OS scan
        type: boolean
        required: false
        default: false
      trivy-os-ignore-unfixed:
        description: Ignore unfixed vulnerabilities in Trivy OS scan
        type: boolean
        required: false
        default: true
      trivy-os-severity:
        description: When to fail the scan with Trivy OS vulnerabilities
        type: string
        required: false
        default: 'CRITICAL'
      trivy-version:
        description: Version of Trivy to use for scanning
        type: string
        required: false
        default: ''

jobs:
  build-and-scan-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      DOCKLE_HOST: "unix:///var/run/docker.sock"
      #TRIVY_TIMEOUT: "15m"
    steps:
      - name: Set image metadata
        id: image-metadata
        uses: felleslosninger/github-workflows/.github/actions/image-metadata@main
        with:
          image-name: ${{ inputs.image-name }}
          container-registry: "my-local-registry"

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v6.0.2

      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # pin@v5.2.0
        with:
          distribution: "${{ inputs.java-distribution }}"
          java-version: ${{ inputs.java-version }}
          cache: maven
          cache-dependency-path: ${{ inputs.cache-path }}
          server-id: github
          server-username: GH_PACKAGES_READ_USER
          server-password: GH_PACKAGES_READ_PAT

      - name: Install pack
        run: |
          #!/usr/bin/env bash
          set -euo pipefail
          echo "Installing pack ${PACK_VERSION}"
          mkdir -p /usr/local/bin
          curl \
            --location \
            --show-error \
            --silent \
            "https://github.com/buildpacks/pack/releases/download/v${PACK_VERSION}/pack-v${PACK_VERSION}-linux.tgz" \
          | sudo tar -C /usr/local/bin --no-same-owner -xzv pack
        env:
          PACK_VERSION: 0.39.1

      - name: Build native image with Maven/Quarkus
        if: inputs.native == true
        env:
          GH_PACKAGES_READ_USER: ${{ secrets.GH_PACKAGES_READ_USER }}
          GH_PACKAGES_READ_PAT: ${{ secrets.GH_PACKAGES_READ_PAT }}
        run: |
          pack build ${{ steps.image-metadata.outputs.image-name }}:${{ steps.image-metadata.outputs.image-tag }} \
            --path . \
            --buildpack docker://paketobuildpacks/quarkus \
            --buildpack docker://paketobuildpacks/java-native-image \
            --builder paketobuildpacks/${{ inputs.image-pack }}:${{ inputs.image-pack-tag }} \
            --volume "${HOME}/.m2:/home/cnb/.m2:rw" \
            --env BP_JVM_VERSION="${{ inputs.java-version }}" \
            --env BP_MAVEN_POM_FILE="./pom.xml" \
            --env BP_NATIVE_IMAGE="true" \
            --env LANG="C.UTF-8" \
            --env GH_PACKAGES_READ_USER="${{ env.GH_PACKAGES_READ_USER }}" \
            --env GH_PACKAGES_READ_PAT="${{ env.GH_PACKAGES_READ_PAT }}" \
            --creation-time now

      - name: Build image with Maven/Quarkus
        if: inputs.native == false
        env:
          GH_PACKAGES_READ_USER: ${{ secrets.GH_PACKAGES_READ_USER }}
          GH_PACKAGES_READ_PAT: ${{ secrets.GH_PACKAGES_READ_PAT }}
        run: |
          pack build ${{ steps.image-metadata.outputs.image-name }}:${{ steps.image-metadata.outputs.image-tag }} \
            --path . \
            --buildpack docker://paketobuildpacks/quarkus \
            --buildpack docker://paketobuildpacks/java \
            --builder paketobuildpacks/${{ inputs.image-pack }}:${{ inputs.image-pack-tag }} \
            --volume "${HOME}/.m2:/home/cnb/.m2:rw" \
            --env BP_JVM_VERSION="${{ inputs.java-version }}" \
            --env BP_MAVEN_POM_FILE="./pom.xml" \
            --env GH_PACKAGES_READ_USER="${{ env.GH_PACKAGES_READ_USER }}" \
            --env GH_PACKAGES_READ_PAT="${{ env.GH_PACKAGES_READ_PAT }}" \
            --creation-time now

      - name: Run Trivy vulnerability scanner
        uses: felleslosninger/github-workflows/.github/actions/trivy-scan@main
        with:
          image-ref: "${{ steps.image-metadata.outputs.image-name }}:${{ steps.image-metadata.outputs.image-tag }}"
          application-path: ${{ inputs.application-path }}
          library-disable-scan: ${{ inputs.trivy-library-disable-scan }}
          library-ignore-unfixed: ${{ inputs.trivy-library-ignore-unfixed }}
          library-severity: ${{ inputs.trivy-library-severity }}
          os-disable-scan: ${{ inputs.trivy-os-disable-scan }}
          os-ignore-unfixed: ${{ inputs.trivy-os-ignore-unfixed }}
          os-severity: ${{ inputs.trivy-os-severity }}
          trivy-version: ${{ inputs.trivy-version }}
