name: Container scan

on:
  workflow_call:
    inputs:
      image-name:
        description: Name of Docker image
        required: false
        type: string
      image-pack:
        description: Paketo builder image to use. See https://paketo.io/docs/reference/builders-reference/ for choices
        default: builder-noble-java-tiny
        required: false
        type: string
      image-pack-tag:
        description: "Docker image pack version tag. Earlier pinned to 0.0.440 due to lifecycle 0.21.2 regression (see: paketo-buildpacks/builder-noble-java-tiny#191). Now fixed: https://github.com/paketo-buildpacks/builder-noble-java-tiny/issues/191#issuecomment-3897508140"
        default: "latest"
        required: false
        type: string
      registry-url:
        description: Image/Container Registery URL
        default: "my-local-registery"
        required: false
        type: string
      java-version:
        description: Main version of java
        default: "11"
        required: false
        type: string
      java-distribution:
        description: Java distribution to use
        default: "liberica"
        required: false
        type: string
      cache-path:
        default: "**/pom.xml"
        required: false
        type: string
      native:
        description: Build native image
        required: false
        type: boolean
        default: false
      application-path:
        default: "./"
        required: false
        type: string
      trivy-library-disable-scan:
        description: Disable Trivy library scan
        type: boolean
        required: false
        default: false
      trivy-library-ignore-unfixed:
        description: Ignore unfixed vulnerabilities in Trivy library scan
        type: boolean
        required: false
        default: true
      trivy-library-severity:
        description: When to fail the scan with Trivy library vulnerabilities
        type: string
        required: false
        default: 'HIGH,CRITICAL'
      trivy-os-disable-scan:
        description: Disable Trivy OS scan
        type: boolean
        required: false
        default: false
      trivy-os-ignore-unfixed:
        description: Ignore unfixed vulnerabilities in Trivy OS scan
        type: boolean
        required: false
        default: true
      trivy-os-severity:
        description: When to fail the scan with Trivy OS vulnerabilities
        type: string
        required: false
        default: 'CRITICAL'
      trivy-version:
        description: Version of Trivy to use for scanning
        type: string
        required: false
        default: ''

jobs:
  build-and-scan-image:
    runs-on: ubuntu-latest
    env:
      REPOSITORY-NAME: ${{ github.event.repository.name }}
      DOCKLE_HOST: "unix:///var/run/docker.sock"
      #TRIVY_TIMEOUT: "15m"
    steps:
      - name: Set imagetag as env variable
        run: echo "IMAGETAG=$(date +'%Y-%m-%d-%H%M')-${GITHUB_SHA::8}" >> "$GITHUB_ENV"

      - name: Set IMAGE-NAME env variable
        run: |
          echo "IMAGE-NAME=${{ inputs.registry-url }}/${{ inputs.image-name || env.REPOSITORY-NAME }}" >> "$GITHUB_ENV"

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # pin@v5.0.0

      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # pin@v5.0.0
        with:
          distribution: "${{ inputs.java-distribution }}"
          java-version: ${{ inputs.java-version }}
          cache: maven
          cache-dependency-path: ${{ inputs.cache-path }}
          server-id: github
          server-username: MAVEN_USER
          server-password: MAVEN_PASSWORD

      - name: Install pack
        run: |
          #!/usr/bin/env bash
          set -euo pipefail
          echo "Installing pack ${PACK_VERSION}"
          mkdir -p /usr/local/bin
          curl \
            --location \
            --show-error \
            --silent \
            "https://github.com/buildpacks/pack/releases/download/v${PACK_VERSION}/pack-v${PACK_VERSION}-linux.tgz" \
          | sudo tar -C /usr/local/bin --no-same-owner -xzv pack
        env:
          PACK_VERSION: 0.39.1

      - name: Build native image with Maven/Quarkus
        if: inputs.native == true
        env:
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: |
          pack build ${{env.IMAGE-NAME}}:${{env.IMAGETAG}} \
            --path . \
            --buildpack docker://paketobuildpacks/quarkus \
            --buildpack docker://paketobuildpacks/java-native-image \
            --builder paketobuildpacks/${{ inputs.image-pack }}:${{ inputs.image-pack-tag }} \
            --volume "${HOME}/.m2:/home/cnb/.m2:rw" \
            --env BP_JVM_VERSION="${{ inputs.java-version }}" \
            --env BP_MAVEN_POM_FILE="./pom.xml" \
            --env BP_NATIVE_IMAGE="true" \
            --env LANG="C.UTF-8" \
            --env MAVEN_USER="${{ env.MAVEN_USER }}" \
            --env MAVEN_PASSWORD="${{ env.MAVEN_PASSWORD }}" \
            --creation-time now

      - name: Build image with Maven/Quarkus
        if: inputs.native == false
        env:
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        run: |
          pack build ${{env.IMAGE-NAME}}:${{env.IMAGETAG}} \
            --path . \
            --buildpack docker://paketobuildpacks/quarkus \
            --buildpack docker://paketobuildpacks/java \
            --builder paketobuildpacks/${{ inputs.image-pack }}:${{ inputs.image-pack-tag }} \
            --volume "${HOME}/.m2:/home/cnb/.m2:rw" \
            --env BP_JVM_VERSION="${{ inputs.java-version }}" \
            --env BP_MAVEN_POM_FILE="./pom.xml" \
            --env MAVEN_USER="${{ env.MAVEN_USER }}" \
            --env MAVEN_PASSWORD="${{ env.MAVEN_PASSWORD }}" \
            --creation-time now

      - name: Run Trivy vulnerability scanner
        uses: felleslosninger/github-workflows/.github/actions/trivy-scan@main
        with:
          image-ref: ${{env.IMAGE-NAME}}:${{env.IMAGETAG}}
          application-path: ${{ inputs.application-path }}
          library-disable-scan: ${{ inputs.trivy-library-disable-scan }}
          library-ignore-unfixed: ${{ inputs.trivy-library-ignore-unfixed }}
          library-severity: ${{ inputs.trivy-library-severity }}
          os-disable-scan: ${{ inputs.trivy-os-disable-scan }}
          os-ignore-unfixed: ${{ inputs.trivy-os-ignore-unfixed }}
          os-severity: ${{ inputs.trivy-os-severity }}
          trivy-version: ${{ inputs.trivy-version }}
