name: Build k6-docker

on:
  workflow_call:
    inputs:
      image-name:
        description: Name of Docker image
        required: false
        type: string
      k6-folder:
        description: Folder with k6-tests
        default: 'k6-load-tests'
        required: false
        type: string
      k6-libs-folder:
        description: Folder with k6-tests
        default: 'libs'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPOSITORY-NAME: ${{ github.event.repository.name }}
      REGISTRY_URL: my-local-registry
      DOCKLE_HOST: "unix:///var/run/docker.sock"
    steps:
      - name: Set imagetag as env variable
        run: echo "IMAGETAG=$(date +'%Y-%m-%d-%H%M')-${GITHUB_SHA::8}" >> "$GITHUB_ENV"
      - name: Set IMAGE-NAME env variable
        run: |
           echo "IMAGE-NAME=${{ env.REGISTRY_URL }}/${{ inputs.image-name || env.REPOSITORY-NAME }}" >> "$GITHUB_ENV"
      - uses: actions/checkout@v3
      - name: Copy k6-tests to docker temp
        run: |
          cp -R ${{ inputs.k6-folder }}/* docker/k6-tests/
          cp -R ${{ inputs.k6-libs-folder }}/* docker/${{ inputs.k6-libs-folder }}/
      - name: Build the tagged Docker image
        run: docker build --tag ${{env.IMAGE-NAME}}:${{env.IMAGETAG}} docker/
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@41f05d9ecffa2ed3f1580af306000f734b733e54 # pin@v0.11.2
        with:
          image-ref: ${{env.IMAGE-NAME}}:${{env.IMAGETAG}}
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          
