name: dev.docker build and release to crutvikling registry

on:
  workflow_call:
    inputs:
      docker-file:
        description: Location and name of Dockerfile
        required: false
        type: string
        default: docker/dev.Dockerfile

jobs:
  docker-build-publish:
    runs-on: ubuntu-latest
    env:
      REPOSITORY-NAME: ${{ github.event.repository.name }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to crutvikling container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.CR_DEV_URL }}
          username: ${{ secrets.CR_DEV_USERNAME }}
          password: ${{ secrets.CR_DEV_SECRET }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            GIT_PACKAGE_USERNAME=${{ secrets.GH_PACKAGES_READ_USER }}
            GIT_PACKAGE_TOKEN=${{ secrets.GH_PACKAGES_READ_PAT }}
          file: ${{ inputs.docker-file }}
          labels: dev
          tags: ${{ vars.CR_DEV_URL }}/${{env.REPOSITORY-NAME}}:latest
          
