# Workflow Name: Dependabot Approve and Merge
#
# Owner: Digdir Platform team
#
# Purpose:
#   This is part of the golden path for PRs towards main branch. The workflow
#   should not be used directly, but is called from the ci-pr-checks
#   workflow, which checks certain things before calling this workflow with the
#   correct parameters. This workflow will only run for PRs created by
#   Dependabot, and will auto-approve and auto-merge the PR if the update type
#   is supported. The supported update types are defined in the input section,
#   and the workflow will check the update type of the PR against the supported
#   types before attempting to approve and merge. If the update type is not
#   supported, the workflow will skip the PR and write a summary note about the
#   unsupported update type. The workflow will also write a summary note about
#   the result of the workflow, whether it was auto-merged or skipped due to
#   unsupported update type. The workflow is designed to be flexible and can be
#   easily extended to support more update types by simply updating the input
#   parameter with the new supported types. The workflow uses the GitHub CLI
#   (gh) to interact with the PR, which allows for more control and flexibility
#   in the approval and merging process. The workflow also uses the Dependabot/
#   fetch-metadata action to fetch the metadata of the Dependabot PR, which
#   includes the update type, allowing the workflow to make informed decisions
#   about whether to approve and merge the PR based on the update type.
#
#   Flow:
#     1. Checkout repository
#     2. Fetch update types from input parameter
#     3. Fetch Dependabot metadata (including update type)
#     4. If the update type is supported, approve and auto-merge the PR
#     5. Write summary note about the result of the workflow
#
# Trigger:
#   Triggered by workflow calls (workflow_call)
#
# Inputs:
#   See input section
#
# Outputs:
#   See output section
#

name: Dependabot Approve and Merge

permissions: {}

on:
  workflow_call:
    inputs:
      update-types:
        description: Dependabot update types to auto-merge (check out possible 'update-types' in https://docs.github.com/en/code-security/reference/supply-chain-security/dependabot-options-reference#allow--). The default will ensure auto-merge of patch and minor version updates
        default: "version-update:semver-patch;version-update:semver-minor"
        required: false
        type: string
    outputs:
      merged:
        description: Whether the PR was merged or not (true|false)
        value: ${{ jobs.dependabot.outputs.merged }}

jobs:
  dependabot:
    name: Auto approve
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      merged: ${{ steps.write-summary.outputs.merged }}

    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v6.0.2

      - name: Fetch update types
        id: update-types
        env:
          UPDATE_TYPES: ${{ inputs.update-types }}
        run: |
          IFS=';' read -ra arr <<< "$UPDATE_TYPES"
          count=${#arr[@]}

          echo "Types: ${arr[*]}"
          echo "Count: ${count}"
          echo "types=${arr[*]}" >> "$GITHUB_OUTPUT"
          echo "count=${count}" >> "$GITHUB_OUTPUT"

      - name: Fetch Dependabot metadata
        if: fromJson(steps.update-types.outputs.count) > 0
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@25dd0e34f4fe68f24cc83900b1fe3fe149efef98 # pin@v3.1.0

      - name: Approve and auto-merge
        id: auto-merge
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: fromJson(steps.update-types.outputs.count) > 0 && contains(steps.update-types.outputs.types, steps.dependabot-metadata.outputs.update-type)
        run: |
          gh pr edit "$PR_URL" --add-label "auto-merged"
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --squash "$PR_URL"
          echo "status=true" >> "$GITHUB_OUTPUT"

      - name: Write summary
        id: write-summary
        env:
          MERGE_STATUS: ${{ steps.auto-merge.outputs.status }}
          UPDATE_TYPE: ${{ steps.dependabot-metadata.outputs.update-type }}
          INPUT_TYPES: ${{ inputs.update-types }}
        run: |
          echo "### Dependabot auto-merge results" >> "$GITHUB_STEP_SUMMARY"

          if [ "$MERGE_STATUS" == "true" ]; then
            echo "- :white_check_mark: Done with auto-merge!" >> "$GITHUB_STEP_SUMMARY"
            echo "merged=true" >> "$GITHUB_OUTPUT"
          else
            {
              echo "- :x: Skipped because of unsupported update type: $UPDATE_TYPE"
              echo "> [!NOTE]"
              echo "> Supported types are:"
              echo "> $INPUT_TYPES"
            } >> "$GITHUB_STEP_SUMMARY"
            echo "merged=false" >> "$GITHUB_OUTPUT"
          fi
