name: dev.docker build and release to crutvikling (Azure container registry)

on:
  workflow_call:
    inputs:
      docker-file:
        description: Location and name of Dockerfile
        required: false
        type: string
        default: docker/dev.Dockerfile

jobs:
  docker-build-publish:
    runs-on: ubuntu-latest
    env:
      REPOSITORY-NAME: ${{ github.event.repository.name }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # pin@v3.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # pin@v3.0.0

      - name: Login to crutvikling (Azure container registry)
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # pin@v3.3.0
        with:
          registry: ${{ vars.CR_DEV_URL }}
          username: ${{ secrets.CR_DEV_USERNAME }}
          password: ${{ secrets.CR_DEV_SECRET }}

      - name: Build and push
        uses: docker/build-push-action@67a2d409c0a876cbe6b11854e3e25193efe4e62d # pin@v6.12.0
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            GIT_PACKAGE_USERNAME=${{ secrets.GH_PACKAGES_READ_USER }}
            GIT_PACKAGE_TOKEN=${{ secrets.GH_PACKAGES_READ_PAT }}
          file: ${{ inputs.docker-file }}
          labels: dev
          tags: ${{ vars.CR_DEV_URL }}/${{env.REPOSITORY-NAME}}:latest
