---
name: Dependabot Approve and Merge

on:
  workflow_call:
    inputs:
      update-types:
        description: Update types
        default: "version-update:semver-patch;version-update:semver-minor"
        required: false
        type: string
    outputs:
      merged:
        value: ${{ jobs.dependabot.outputs.merged }}

permissions:
  pull-requests: write
  contents: write
  issues: write
  packages: write
  repository-projects: read

jobs:
  dependabot:
    name: Auto approve
    runs-on: ubuntu-latest
    outputs:
      merged: ${{ steps.write-summary.outputs.merged }}

    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    steps:
      - name: Fetch update types
        id: update-types
        env:
          UPDATE_TYPES: ${{ inputs.update-types }}
        run: |
          arr="(${UPDATE_TYPES//;/ })"
          count=${#arr[@]}
          echo "Types: ${arr[*]}"
          echo "Count: ${count}"
          echo "types=${arr[*]}" >> "$GITHUB_OUTPUT"
          echo "count=${count}" >> "$GITHUB_OUTPUT"

      - name: Fetch Dependabot metadata
        if: ${{ fromJson(steps.update-types.outputs.count) > 0 }}
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.6.0

      - name: Approve and auto-merge
        id: auto-merge
        if: ${{ fromJson(steps.update-types.outputs.count) > 0 && contains(steps.update-types.outputs.types, steps.dependabot-metadata.outputs.update-type) }}
        run: |
          gh pr edit "$PR_URL" --add-label "auto-merged"
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --squash "$PR_URL"
          echo "status=true" >> "$GITHUB_OUTPUT"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Write summary
        id: write-summary
        run: |
          echo "# Results" >> "$GITHUB_STEP_SUMMARY"
          if [ ${{ steps.auto-merge.outputs.status }} == "true" ]; then
            echo "- Done with auto-merge! :white_check_mark:" >> "$GITHUB_STEP_SUMMARY"
            echo "merged=true" >> "$GITHUB_OUTPUT"
          else
            {
              echo "- Skipped because of unsupported update type, ${{ steps.dependabot-metadata.outputs.update-type}} :x:"
              echo "> [!NOTE]"
              echo "> Supported types are:"
              echo "> ${{ inputs.update-types }}"
            } >> "$GITHUB_STEP_SUMMARY" 
            echo "merged=false" >> "$GITHUB_OUTPUT"
          fi
