---
name: Dependabot Approve and Merge

on:
  workflow_call:
    inputs:
      update-types:
        description: Update types
        default: "version-update:semver-patch;version-update:semver-minor"
        required: false
        type: string

permissions:
  pull-requests: write
  contents: write
  issues: write
  packages: write
  repository-projects: read

jobs:
  dependabot:
    name: Auto approve
    runs-on: ubuntu-latest

    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    steps:
      - name: Install Dependencies
        run: npm install @octokit/app@v14.0.2

      - name: Generate Token
        uses: actions/github-script@v7
        id: generate-token
        env:
          GH_APP_ID: ${{ secrets.DIGDIR_PLATFORM_CD_APP_ID }}
          GH_APP_PRIVATE_KEY: ${{ secrets.DIGDIR_PLATFORM_CD_APP_PRIVATE_KEY }}
          INSTALLATION_ID: ${{ secrets.DIGDIR_PLATFORM_CD_APP_INSTALLATION_ID }}
        with:
          script: |
            const { createAppAuth } = require("@octokit/auth-app");

            const auth = createAppAuth({
              appId: +process.env.GH_APP_ID,
              privateKey: process.env.GH_APP_PRIVATE_KEY
            });

            const { token } = await auth({ type: "installation", installationId: +process.env.INSTALLATION_ID });

            core.setOutput('token', token);
          result-encoding: string

      - name: Fetch update types
        id: update-types
        env:
          UPDATE_TYPES: ${{ inputs.update-types }}
        run: |
          arr="(${UPDATE_TYPES//;/ })"
          count=${#arr[@]}
          echo "Types: ${arr[*]}"
          echo "Count: ${count}"
          echo "types=${arr[*]}" >> "$GITHUB_OUTPUT"
          echo "count=${count}" >> "$GITHUB_OUTPUT"

      - name: Fetch Dependabot metadata
        if: ${{ fromJson(steps.update-types.outputs.count) > 0 }}
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.6.0

      - name: Approve and auto-merge
        id: auto-merge
        if: ${{ fromJson(steps.update-types.outputs.count) > 0 && contains(steps.update-types.outputs.types, steps.dependabot-metadata.outputs.update-type) }}
        run: |
          gh pr edit "$PR_URL" --add-label "auto-merged"
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --squash "$PR_URL"
          echo "status=true" >> "$GITHUB_OUTPUT"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Write summary
        id: write-summary
        run: |
          echo "# Results" >> "$GITHUB_STEP_SUMMARY"
          if [ ${{ steps.auto-merge.outputs.status }} == "true" ]; then
            echo "- Done with auto-merge! :white_check_mark:" >> "$GITHUB_STEP_SUMMARY"
          else
            {
              echo "- Skipped because of unsupported update type, ${{ steps.dependabot-metadata.outputs.update-type}} :x:"
              echo "> [!NOTE]"
              echo "> Supported types are:"
              echo "> ${{ inputs.update-types }}"
            } >> "$GITHUB_STEP_SUMMARY" 
          fi
