# Workflow Name: Build/publish custom Docker development image to ACR
#
# Owner: Digdir Platform team / Digdir development teams
#
# Purpose:
#   This workflow is responsible for building and publishing a custom Docker
#   development image to Azure Container Registry (ACR). The workflow is
#   designed to be triggered by an app repo workflow on a new main commit. The
#   workflow will build a Docker image based on a specified Dockerfile in the
#   app repos, and push it to our 'crutvikling' development ACR. The image will
#   always be tagged with 'latest' to ensure that the most recent development
#   image is easily accessible. The workflow uses Docker Buildx to build
#   multi-platform images for both amd64 and arm64 architectures, ensuring
#   compatibility with a wide range of development environments. The workflow
#   also includes a step to set up QEMU, which allows for building images for
#   different architectures on the same runner.
#
#   Flow:
#     1. Set up QEMU for multi-platform builds
#     2. Set up Docker Buildx
#     3. Login to 'crutvikling' Azure Container Registry (ACR)
#     4. Build and push Docker image to ACR with 'latest' tag for both amd64
#        and arm64 platforms
#
# Trigger:
#   Triggered by workflow calls (workflow_call)
#
# Inputs:
#   See input section
#
# Outputs:
#   None
#

name: Build/publish custom Docker development image to ACR

permissions: {}

on:
  workflow_call:
    inputs:
      docker-file:
        description: Location and name of Dockerfile
        required: false
        type: string
        default: docker/dev.Dockerfile

jobs:
  docker-build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      REPOSITORY-NAME: ${{ github.event.repository.name }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # pin@v4.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # pin@v4.0.0

      - name: Login to crutvikling (Azure container registry)
        uses: docker/login-action@06fb636fac595d6fb4b28a5dfcb21a6f5091859c # pin@v4.5.0
        with:
          registry: ${{ vars.CR_DEV_URL }}
          username: ${{ secrets.CR_DEV_USERNAME }}
          password: ${{ secrets.CR_DEV_SECRET }}

      - name: Build and push
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # pin@v7.1.0
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            GIT_PACKAGE_USERNAME=${{ secrets.GH_PACKAGES_READ_USER }}
            GIT_PACKAGE_TOKEN=${{ secrets.GH_PACKAGES_READ_PAT }}
          file: ${{ inputs.docker-file }}
          labels: dev
          tags: ${{ vars.CR_DEV_URL }}/${{env.REPOSITORY-NAME}}:latest
