name: On PR label

on:
  workflow_call:

env:
  internal-commit-string: "//INTERNAL-COMMIT"

jobs:
  append-internal-commit-string-to-title:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'internal'
    steps:
      - name: Append ${{ env.append-string }} to PR title
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { pull_request } = context.payload;
            const newTitle = `${pull_request.title} ${{ env.internal-commit-string }}`;
            
            if (!pull_request.title.includes("${{ env.internal-commit-string }}")) {
              const response = await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pull_request.number,
                title: newTitle,
              });
              core.info("PR title updated to " + response.data.title);
            } else {
              core.info("PR title already contains ${{ env.internal-commit-string }}");
            }
