name: On PR label

permissions: {}

on:
  workflow_call:

env:
  internal-commit-string: "(INTERNAL-COMMIT)"

jobs:
  append-internal-commit-string-to-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.event.label.name == 'internal'
    steps:
      - name: Append ${{ env.internal-commit-string }} to PR title
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # pin@v9.0.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { pull_request } = context.payload;
            const newTitle = `${pull_request.title} ${{ env.internal-commit-string }}`;

            if (!pull_request.title.includes("${{ env.internal-commit-string }}")) {
              const response = await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pull_request.number,
                title: newTitle,
              });
              core.info("PR title updated to " + response.data.title);
            } else {
              core.info("PR title already contains ${{ env.internal-commit-string }}");
            }
