name: Append [[INTERNAL]] to PR Title

on:
  pull_request_target:
    types: [labeled]

jobs:
  append-internal-to-title:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'internal'
    steps:
      - name: Append [[INTERNAL]] to PR title
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { pull_request } = context.payload;
            const newTitle = `${pull_request.title} [[INTERNAL]]`;
            
            if (!pull_request.title.includes('[[INTERNAL]]')) {
              const response = await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pull_request.number,
                title: newTitle,
              });
              console.log("PR title updated", response.data.title);
            } else {
              console.log("PR title already contains [[INTERNAL]]");
            }
